-- Extensão para geração de UUID se necessário
create extension if not exists "uuid-ossp";

-- 1. TABELA: responsaveis
create table if not exists public.responsaveis (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    nome text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.responsaveis enable row level security;

-- Políticas RLS
create policy "Usuários podem ver apenas seus próprios responsáveis"
    on public.responsaveis for select
    using (auth.uid() = user_id);

create policy "Usuários podem inserir seus próprios responsáveis"
    on public.responsaveis for insert
    with check (auth.uid() = user_id);

create policy "Usuários podem atualizar seus próprios responsáveis"
    on public.responsaveis for update
    using (auth.uid() = user_id);

create policy "Usuários podem deletar seus próprios responsáveis"
    on public.responsaveis for delete
    using (auth.uid() = user_id);


-- 2. TABELA: categorias
create table if not exists public.categorias (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    nome text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.categorias enable row level security;

-- Políticas RLS
create policy "Usuários podem ver apenas suas próprias categorias"
    on public.categorias for select
    using (auth.uid() = user_id);

create policy "Usuários podem inserir suas próprias categorias"
    on public.categorias for insert
    with check (auth.uid() = user_id);

create policy "Usuários podem atualizar suas próprias categorias"
    on public.categorias for update
    using (auth.uid() = user_id);

create policy "Usuários podem deletar suas próprias categorias"
    on public.categorias for delete
    using (auth.uid() = user_id);


-- 3. TABELA: cartoes
create table if not exists public.cartoes (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    nome text not null,
    cor text not null default '#64748b',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.cartoes enable row level security;

-- Políticas RLS
create policy "Usuários podem ver apenas seus próprios cartões"
    on public.cartoes for select
    using (auth.uid() = user_id);

create policy "Usuários podem inserir seus próprios cartões"
    on public.cartoes for insert
    with check (auth.uid() = user_id);

create policy "Usuários podem atualizar seus próprios cartões"
    on public.cartoes for update
    using (auth.uid() = user_id);

create policy "Usuários podem deletar seus próprios cartões"
    on public.cartoes for delete
    using (auth.uid() = user_id);


-- 4. TABELA: lancamentos
create table if not exists public.lancamentos (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    descricao text not null,
    valor numeric(12, 2) not null,
    mes text not null, -- formato 'AAAA-MM' (ex: '2026-06')
    responsavel_id bigint references public.responsaveis(id) on delete set null,
    cartao_id bigint references public.cartoes(id) on delete set null,
    categoria_id bigint references public.categorias(id) on delete set null,
    parcela text not null default 'À vista',
    grupo_id text, -- ID de agrupamento para parcelamento
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.lancamentos enable row level security;

-- Políticas RLS
create policy "Usuários podem ver apenas seus próprios lançamentos"
    on public.lancamentos for select
    using (auth.uid() = user_id);

create policy "Usuários podem inserir seus próprios lançamentos"
    on public.lancamentos for insert
    with check (auth.uid() = user_id);

create policy "Usuários podem atualizar seus próprios lançamentos"
    on public.lancamentos for update
    using (auth.uid() = user_id);

create policy "Usuários podem deletar seus próprios lançamentos"
    on public.lancamentos for delete
    using (auth.uid() = user_id);


-- 5. TRIGGER & FUNÇÃO PARA INSERIR VALORES PADRÃO PARA NOVOS USUÁRIOS
create or replace function public.handle_new_user()
returns trigger as $$
begin
    -- Inserir responsáveis padrão
    insert into public.responsaveis (user_id, nome)
    values 
        (new.id, 'Amor'),
        (new.id, 'Wandernilson');

    -- Inserir cartões padrão com suas cores
    insert into public.cartoes (user_id, nome, cor)
    values 
        (new.id, 'Nubank', '#8b5cf6'),
        (new.id, 'PicPay', '#10b981'),
        (new.id, 'Next', '#22c55e'),
        (new.id, 'Inter', '#f97316'),
        (new.id, 'C6', '#1e293b'),
        (new.id, 'Mercado Pago', '#3b82f6'),
        (new.id, 'Pix', '#06b6d4'),
        (new.id, 'Dinheiro', '#475569'),
        (new.id, 'Outros', '#94a3b8');

    -- Inserir categorias padrão
    insert into public.categorias (user_id, nome)
    values 
        (new.id, 'Alimentação'),
        (new.id, 'Assinatura'),
        (new.id, 'Compras'),
        (new.id, 'Consulta'),
        (new.id, 'Dentista'),
        (new.id, 'Eletrônico'),
        (new.id, 'Empréstimo'),
        (new.id, 'Exame'),
        (new.id, 'Faculdade/Pós'),
        (new.id, 'Farmácia'),
        (new.id, 'Imposto'),
        (new.id, 'Juros'),
        (new.id, 'Internet'),
        (new.id, 'Internet Móvel'),
        (new.id, 'Investimentos'),
        (new.id, 'Manutenção'),
        (new.id, 'Pagamento'),
        (new.id, 'Parcela Casa'),
        (new.id, 'Pets'),
        (new.id, 'Pix mensal'),
        (new.id, 'Plano de saúde'),
        (new.id, 'Plano odontológico'),
        (new.id, 'Reserva de emergência'),
        (new.id, 'Roupas'),
        (new.id, 'Salão/Barbearia'),
        (new.id, 'Saúde pessoal'),
        (new.id, 'Supermercado'),
        (new.id, 'Transporte'),
        (new.id, 'Transporte público');

    return new;
end;
$$ language plpgsql security definer;

-- Associar gatilho à tabela auth.users
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();
